import { PGlite } from '@electric-sql/pglite'

export type Project = {
  id: number
  name: string
  roles: string[]
  useCases: string[]
}

export type CreateProjectInput = {
  name: string
  roles: string[]
  useCases: string[]
}

export type ProjectRepository = {
  listProjects: () => Promise<Project[]>
  getProject: (projectId: number) => Promise<Project | null>
  createProject: (input: CreateProjectInput) => Promise<Project>
  addProjectRole: (projectId: number, role: string) => Promise<Project | null>
  addProjectUseCase: (projectId: number, useCase: string) => Promise<Project | null>
  updateProjectUseCase: (projectId: number, currentUseCase: string, nextUseCase: string) => Promise<Project | null>
  removeProjectUseCase: (projectId: number, useCase: string) => Promise<Project | null>
}

type DbProject = {
  id: number
  name: string
}

type DbValue = {
  value: string
}

let dbPromise: Promise<PGlite> | null = null

async function getDatabase() {
  if (!dbPromise) {
    dbPromise = (async () => {
      const db = new PGlite('idb://specs-projects-db')
      await db.exec(`
        CREATE TABLE IF NOT EXISTS projects (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS project_roles (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
          value TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS project_use_cases (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
          value TEXT NOT NULL
        );
      `)
      return db
    })()
  }

  return dbPromise
}

async function readList(db: PGlite, table: 'project_roles' | 'project_use_cases', projectId: number) {
  const result = await db.query<DbValue>(
    `SELECT value FROM ${table} WHERE project_id = $1 ORDER BY id ASC`,
    [projectId],
  )

  return result.rows.map((entry) => entry.value)
}

async function hydrateProject(db: PGlite, project: DbProject): Promise<Project> {
  const [roles, useCases] = await Promise.all([
    readList(db, 'project_roles', project.id),
    readList(db, 'project_use_cases', project.id),
  ])

  return {
    id: project.id,
    name: project.name,
    roles,
    useCases,
  }
}

function normalizeAndValidateTextField(value: string, fieldLabel: string) {
  const normalizedValue = value.trim()
  if (!normalizedValue) {
    throw new Error(`${fieldLabel} is required`)
  }

  if (normalizedValue.length > 255) {
    throw new Error(`${fieldLabel} exceeds maximum length of 255 characters`)
  }

  return normalizedValue
}

export function createPgliteProjectRepository(): ProjectRepository {
  return {
    async listProjects() {
      const db = await getDatabase()
      const result = await db.query<DbProject>('SELECT id, name FROM projects ORDER BY id DESC')
      return Promise.all(result.rows.map((project) => hydrateProject(db, project)))
    },

    async getProject(projectId) {
      const db = await getDatabase()
      const result = await db.query<DbProject>('SELECT id, name FROM projects WHERE id = $1', [projectId])
      const project = result.rows[0]
      if (!project) {
        return null
      }

      return hydrateProject(db, project)
    },

    async createProject(input) {
      const db = await getDatabase()
      const result = await db.query<DbProject>(
        'INSERT INTO projects (name) VALUES ($1) RETURNING id, name',
        [input.name],
      )
      const project = result.rows[0]

      if (!project) {
        throw new Error('Unable to create project')
      }

      await Promise.all(
        input.roles.map((role) =>
          db.query('INSERT INTO project_roles (project_id, value) VALUES ($1, $2)', [project.id, role]),
        ),
      )

      await Promise.all(
        input.useCases.map((useCase) =>
          db.query('INSERT INTO project_use_cases (project_id, value) VALUES ($1, $2)', [project.id, useCase]),
        ),
      )

      return hydrateProject(db, project)
    },

    async addProjectRole(projectId, role) {
      const db = await getDatabase()
      // hydrateProject needs both id and name to return a complete project payload after update.
      const project = await db.query<DbProject>('SELECT id, name FROM projects WHERE id = $1', [projectId])
      if (!project.rows[0]) {
        return null
      }

      const normalizedRole = normalizeAndValidateTextField(role, 'Role')
      const existingRole = await db.query<{ id: number }>(
        'SELECT id FROM project_roles WHERE project_id = $1 AND value = $2 LIMIT 1',
        [projectId, normalizedRole],
      )

      if (existingRole.rows.length === 0) {
        await db.query('INSERT INTO project_roles (project_id, value) VALUES ($1, $2)', [projectId, normalizedRole])
      }

      return hydrateProject(db, project.rows[0])
    },

    async addProjectUseCase(projectId, useCase) {
      const db = await getDatabase()
      // hydrateProject needs both id and name to return a complete project payload after update.
      const project = await db.query<DbProject>('SELECT id, name FROM projects WHERE id = $1', [projectId])
      if (!project.rows[0]) {
        return null
      }

      const normalizedUseCase = normalizeAndValidateTextField(useCase, 'Use case')
      const existingUseCase = await db.query<{ id: number }>(
        'SELECT id FROM project_use_cases WHERE project_id = $1 AND value = $2 LIMIT 1',
        [projectId, normalizedUseCase],
      )

      if (existingUseCase.rows.length === 0) {
        await db.query('INSERT INTO project_use_cases (project_id, value) VALUES ($1, $2)', [
          projectId,
          normalizedUseCase,
        ])
      }

      return hydrateProject(db, project.rows[0])
    },

    async updateProjectUseCase(projectId, currentUseCase, nextUseCase) {
      const db = await getDatabase()
      const project = await db.query<DbProject>('SELECT id, name FROM projects WHERE id = $1', [projectId])
      if (!project.rows[0]) {
        return null
      }

      const normalizedCurrentUseCase = normalizeAndValidateTextField(currentUseCase, 'Use case')
      const normalizedNextUseCase = normalizeAndValidateTextField(nextUseCase, 'Use case')

      const currentUseCaseResult = await db.query<{ id: number }>(
        'SELECT id FROM project_use_cases WHERE project_id = $1 AND value = $2 LIMIT 1',
        [projectId, normalizedCurrentUseCase],
      )
      const currentUseCaseRecord = currentUseCaseResult.rows[0]
      if (!currentUseCaseRecord) {
        throw new Error('Use case not found')
      }

      if (normalizedCurrentUseCase !== normalizedNextUseCase) {
        const duplicateUseCase = await db.query<{ id: number }>(
          'SELECT id FROM project_use_cases WHERE project_id = $1 AND value = $2 LIMIT 1',
          [projectId, normalizedNextUseCase],
        )
        if (duplicateUseCase.rows.length > 0) {
          throw new Error('Use case already exists')
        }
      }

      await db.query('UPDATE project_use_cases SET value = $1 WHERE id = $2', [
        normalizedNextUseCase,
        currentUseCaseRecord.id,
      ])

      return hydrateProject(db, project.rows[0])
    },

    async removeProjectUseCase(projectId, useCase) {
      const db = await getDatabase()
      const project = await db.query<DbProject>('SELECT id, name FROM projects WHERE id = $1', [projectId])
      if (!project.rows[0]) {
        return null
      }

      const normalizedUseCase = normalizeAndValidateTextField(useCase, 'Use case')
      const deleteResult = await db.query<{ id: number }>(
        'DELETE FROM project_use_cases WHERE project_id = $1 AND value = $2 RETURNING id',
        [projectId, normalizedUseCase],
      )

      if (deleteResult.rows.length === 0) {
        throw new Error('Use case not found')
      }

      return hydrateProject(db, project.rows[0])
    },
  }
}
